name: "CloudFormation Change Set"
description: "GitHub Action that creates, updates, deletes and applies CloudFormation change sets"
inputs:
  method:
    description: "The action type"
    required: true
  stack_name:
    description: "CloudFormation stack name"
    required: true
  aws_access_key_id:
    description: "aws_access_key_id"
    required: true
  aws_secret_access_key:
    description: "aws_secret_access_key"
    required: true
  aws_region:
    description: "aws_region"
    required: true
  template_file:
    description: "Path to CloudFormation template"
    required: false
  parameters:
    description: Parameters for the template
    required: false
  changeset_name:
    description: Name of changeset
    required: false
outputs:
  changeset_id:
    description: "The changeset id"
  changeset_name:
    description: "The changeset name"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "upload-cloud"
  color: "green"
